name: organizadortarefas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  intl: ^0.19.0
  flutter_gradient_app_bar: ^0.3.1
  carousel_slider: ^4.2.1
  flutter_event_calendar: ^1.0.0
  sqflite: ^2.3.3+2
  path: ^1.9.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
    - assets/image/menu.png
    - assets/image/nave.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
